name: stampede
channels:
  - conda-forge
  - bioconda
dependencies:
  - adjustText
  - anndata
#  - h5py
  - matplotlib
  - natsort
  - numpy
  - pandas <3  # anndata 0.12 cannot handle string columns
  - python >=3.12  # f-strings
  - python-igraph  # sc.tl.leiden
  - scanpy
  - scikit-learn
  - scipy
  - seaborn

# tools
  - geosketch
  - pydeseq2
  - statsmodels

# docs
  - m2r2 >=0.3.2
  - myst-nb
  - pydata-sphinx-theme >=0.17.1
  - sphinx
  - sphinx-autodoc-typehints

# test
  - black
  - ipykernel
  - isort
  - pytest
