name: Build and deploy documentation

on:
  push:
    branches: [main, dev_siebren]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel any in-progress job or run on new event
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: siebrenf/pages@patch-1  # sphinx-notes/pages@v3
      with:
        python_version: 3.12
        installer: uv
